@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Nov 30 22:45:30 -0500 2020
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim time_set_register_testbench_behav -key {Behavioral:sim_1:Functional:time_set_register_testbench} -tclbatch time_set_register_testbench.tcl -view C:/Users/Nick Palladino/Documents/GitHub/palladino_saab_lab4/palladino_saab_lab4/counter_testbench_behav.wcfg -log simulate.log"
call xsim  time_set_register_testbench_behav -key {Behavioral:sim_1:Functional:time_set_register_testbench} -tclbatch time_set_register_testbench.tcl -view C:/Users/Nick Palladino/Documents/GitHub/palladino_saab_lab4/palladino_saab_lab4/counter_testbench_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
